[package]
name = "img-2-anscii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "img2anscii"
path = "src/main.rs"

[dependencies]
clap = "3.2"
img-2-anscii-core = { path = "../img-2-anscii-core" }